#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include "blocks.h"
#include "../parser.tab.h"

extern FILE *yyin; // Input file for the lexer
extern int yydebug;
extern int yyparse(); // Function generated by Bison for parsing

int main(int argc, char **argv) {
    if (argc < 2) {
        fprintf(stderr, "Usage: %s <filename.camp>\n", argv[0]);
        return EXIT_FAILURE;
    }

    srand(time(NULL));

    // Open the input file
    yyin = fopen(argv[1], "r");
    if (!yyin) {
        perror("Error opening file");
        return EXIT_FAILURE;
    }

    yydebug = 1;

    // Start parsing
    if (yyparse() != 0) {
        fprintf(stderr, "Parsing failed.\n");
        fclose(yyin);
        return EXIT_FAILURE;
    }

    fclose(yyin);
    return EXIT_SUCCESS;
}